spring.application.name=CONFIG-SERVER
server.port=8888

eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka

#https://github.com/malekpouri/config-server-rep
spring.cloud.config.server.git.uri=https://github.com/malekpouri/config-server-rep
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.defaultLabel=main

management.endpoints.web.exposure.include=refresh,busrefresh

spring.rabbitmq.host=localhost
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.port=5672